### ISSUE TITLE
服务端后台刷屏最大真实伤害比例数值

### ISSUE THREAD

**Issue by zoe-may** [Ayou0702/RealDamage#1]
![image](https://github.com/user-attachments/assets/e57381eb-7c22-4a71-af42-d7fa7860cc50)
当启用了函数计算，玩家受到伤害会在后台刷屏
版本：1.20.1
服务端：Arclight

**Comment by BelovedYaoo** [comment]
了解，已经定位到问题，是一串调试时忘记注释的代码，稍后修复
